### ISSUE TITLE
how are the readings done?  sleep mode?

### ISSUE THREAD

**Issue by Alain2019** [SV-Zanshin/BME680#30]
Hi

How is de lebrary doing the readings?

After looking at the source code I have the impression that the sensor is constantly running doing measurements.

Is it possible to let it "sleep" and only measure when needed?

Where in the source code should I look?

**Comment by SV-Zanshin** [comment]
Each time a call to [getSensorData()](https://github.com/SV-Zanshin/BME680/wiki/getSensorData())  
 is  made a single measurement is triggered. If no calls to this function are me then no measurements are done. So you control how often readings are done; this is also explained on the wiki page for [getSensorData()](https://github.com/SV-Zanshin/BME680/wiki/getSensorData())

**Comment by Alain2019** [comment]
Ok, thanks

So if I sleep 15 minutes I have to call getSensorData() twice to get a recent measurement?

BTW. I read the doxygen info.

**Comment by SV-Zanshin** [comment]
That is correct, the first returned set of values would be stale, 15 minutes old, and the second set would be the recent values.
